[project]
name = "bert-attack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hf-xet>=1.2.0",
    "pandas>=2.3.3",
    "torch>=2.6.0+cu124",
    "transformers>=4.57.3",
]
